version: "3"
services:
  frontend:
    build: ./frontend
    volumes:
      - ./cert:/cert/
    ports:
      - 0.0.0.0:8623:443
    environment:
      TZ: "Asia/Tokyo"
    restart: always

  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always

  backend:
    build: ./backend
    depends_on:
      - db
    restart: always
