version: "3"
services:
  frontend:
    build: ./frontend
    volumes:
      - ./cert:/cert/
    ports:
      - 0.0.0.0:8623:443
    environment:
      TZ: "Asia/Tokyo"
    restart: always

  db:
    build: ./db
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
    ports:
      - 0.0.0.0:5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Asia/Tokyo"
    restart: always

  backend:
    build: ./backend
    ports:
      - 0.0.0.0:5000:5000
    depends_on:
      - db
    restart: always
